# Generated by Django 2.2 on 2021-03-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='show_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
